import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Loader2 } from 'lucide-react';
import { Language } from '../i18n';
 
interface Quote { author: string; text: string; }
 
const QUOTES: Record<Language, Quote[]> = {
  ru: [
    { author: "Socrates", text: "«Познай самого себя.»" },
    { author: "Socrates", text: "«Красота — это гармония.»" },
    { author: "Friedrich Nietzsche", text: "«Тот, кто имеет зачем жить, выдержит почти любое как.»" },
    { author: "Friedrich Nietzsche", text: "«Красота — обещание счастья.»" },
    { author: "Albert Einstein", text: "«Воображение важнее знания.»" },
    { author: "Albert Einstein", text: "«Всё красивое — просто.»" },
    { author: "Albert Einstein", text: "«Стремись к простоте, но не к простоте мысли.»" },
    { author: "Marcus Aurelius", text: "«Наша жизнь — то, что мы думаем о ней.»" },
    { author: "Marcus Aurelius", text: "«Красота характера важнее внешности.»" },
    { author: "Confucius", text: "«Не останавливайся.»" },
    { author: "Confucius", text: "«Всё имеет красоту, но не каждый её видит.»" },
    { author: "Confucius", text: "«Путь в тысячу миль начинается с одного шага.»" },
    { author: "Seneca", text: "«Страдание чаще в мыслях, чем в реальности.»" },
    { author: "Seneca", text: "«Истинная красота — в душе.»" },
    { author: "Epictetus", text: "«Контролируй реакцию, не события.»" },
    { author: "Epictetus", text: "«Украшай разум, а не тело.»" },
    { author: "Plato", text: "«Начало — главное.»" },
    { author: "Plato", text: "«Красота — сияние истины.»" },
    { author: "Aristotle", text: "«Счастье — в действиях.»" },
    { author: "Aristotle", text: "«Красота — дар природы.»" },
    { author: "Immanuel Kant", text: "«Думай самостоятельно.»" },
    { author: "Immanuel Kant", text: "«Красота — это удовольствие без интереса.»" },
    { author: "Blaise Pascal", text: "«Сердце имеет причины, которых разум не знает.»" },
    { author: "Albert Camus", text: "«В разгар зимы я понял, что внутри меня лето.»" },
    { author: "Carl Jung", text: "«Смотри внутрь.»" },
    { author: "Carl Jung", text: "«Красота — отражение внутреннего.»" },
    { author: "Viktor Frankl", text: "«Смысл находят.»" },
    { author: "Leo Tolstoy", text: "«Где любовь, там жизнь.»" },
    { author: "Leo Tolstoy", text: "«Красота — в простоте.»" },
    { author: "Fyodor Dostoevsky", text: "«Красота спасёт мир.»" },
    { author: "Antoine de Saint-Exupéry", text: "«Зорко одно лишь сердце.»" },
    { author: "Oscar Wilde", text: "«Будь собой.»" },
    { author: "Oscar Wilde", text: "«Красота — форма гения.»" },
    { author: "Oscar Wilde", text: "«Любить себя — начало романа длиною в жизнь.»" },
    { author: "Mark Twain", text: "«Начни.»" },
    { author: "Ernest Hemingway", text: "«Сломать можно, победить — нет.»" },
    { author: "Rumi", text: "«Ты ищешь то, что ищет тебя.»" },
    { author: "Rumi", text: "«Красота — это свет души.»" },
    { author: "Khalil Gibran", text: "«Красота — вечность, смотрящая в зеркало.»" },
    { author: "Paulo Coelho", text: "«Когда ты чего-то хочешь, весь мир помогает тебе.»" },
    { author: "Haruki Murakami", text: "«Боль неизбежна. Страдание — выбор.»" },
    { author: "Coco Chanel", text: "«Красота начинается с решения быть собой.»" },
    { author: "Leonardo da Vinci", text: "«Простота — совершенство.»" },
    { author: "Michelangelo", text: "«Красота уже есть в камне.»" },
    { author: "Vincent van Gogh", text: "«Красота везде.»" },
    { author: "Audrey Hepburn", text: "«Красота женщины — в её глазах.»" },
    { author: "Marilyn Monroe", text: "«Истинная красота — в индивидуальности.»" },
    { author: "Sophia Loren", text: "«Красота — это уверенность.»" },
    { author: "Rihanna", text: "«Красота начинается с уверенности.»" },
    { author: "Marcus Aurelius", text: "«Ты становишься тем, о чём думаешь.»" },
    { author: "Steve Jobs", text: "«Оставайся голодным. Оставайся безрассудным.»" },
    { author: "Steve Jobs", text: "«Иди за своим сердцем.»" },
    { author: "Walt Disney", text: "«Если можешь мечтать — можешь делать.»" },
    { author: "Nelson Mandela", text: "«Я никогда не проигрываю. Я либо побеждаю, либо учусь.»" },
    { author: "Mahatma Gandhi", text: "«Стань тем изменением, которое хочешь увидеть в мире.»" },
    { author: "Maya Angelou", text: "«Мы поднимаемся, помогая другим подняться.»" },
    { author: "Dalai Lama", text: "«Счастье — это состояние ума.»" },
    { author: "Bruce Lee", text: "«Будь как вода.»" },
    { author: "John Lennon", text: "«Жизнь — это то, что происходит, пока ты строишь планы.»" },
    { author: "Mother Teresa", text: "«Любовь начинается с улыбки.»" },
    { author: "Hippocrates", text: "«Пусть пища будет твоим лекарством.»" },
    { author: "Benjamin Franklin", text: "«Инвестиции в знания дают лучший процент.»" },
    { author: "Thomas Edison", text: "«Гений — это 1% вдохновения и 99% труда.»" },
    { author: "Voltaire", text: "«Сомнение — начало мудрости.»" },
    { author: "Ralph Waldo Emerson", text: "«Красота — в глазах смотрящего.»" },
    { author: "George Bernard Shaw", text: "«Жизнь не в поиске себя, а в создании себя.»" },
  ],
  en: [
    { author: "Socrates", text: "«Know thyself.»" },
    { author: "Socrates", text: "«Beauty is harmony.»" },
    { author: "Friedrich Nietzsche", text: "«He who has a why can bear almost any how.»" },
    { author: "Friedrich Nietzsche", text: "«Beauty is a promise of happiness.»" },
    { author: "Albert Einstein", text: "«Imagination is more important than knowledge.»" },
    { author: "Albert Einstein", text: "«Everything beautiful is simple.»" },
    { author: "Albert Einstein", text: "«Strive for simplicity, but not simplicity of thought.»" },
    { author: "Marcus Aurelius", text: "«Our life is what our thoughts make it.»" },
    { author: "Marcus Aurelius", text: "«The beauty of character matters more than appearance.»" },
    { author: "Confucius", text: "«Keep going.»" },
    { author: "Confucius", text: "«Everything has beauty, but not everyone sees it.»" },
    { author: "Confucius", text: "«A journey of a thousand miles begins with a single step.»" },
    { author: "Seneca", text: "«We suffer more in imagination than in reality.»" },
    { author: "Seneca", text: "«True beauty lies in the soul.»" },
    { author: "Epictetus", text: "«Control your reaction, not events.»" },
    { author: "Epictetus", text: "«Adorn the mind, not the body.»" },
    { author: "Plato", text: "«The beginning is the most important part.»" },
    { author: "Plato", text: "«Beauty is the radiance of truth.»" },
    { author: "Aristotle", text: "«Happiness lies in action.»" },
    { author: "Aristotle", text: "«Beauty is a gift of nature.»" },
    { author: "Immanuel Kant", text: "«Think for yourself.»" },
    { author: "Immanuel Kant", text: "«Beauty is pleasure without interest.»" },
    { author: "Blaise Pascal", text: "«The heart has reasons that reason does not know.»" },
    { author: "Albert Camus", text: "«In the middle of winter I found there was an invincible summer in me.»" },
    { author: "Carl Jung", text: "«Look within.»" },
    { author: "Carl Jung", text: "«Beauty is a reflection of the inner self.»" },
    { author: "Viktor Frankl", text: "«Meaning is something you find.»" },
    { author: "Leo Tolstoy", text: "«Where there is love, there is life.»" },
    { author: "Leo Tolstoy", text: "«Beauty lies in simplicity.»" },
    { author: "Fyodor Dostoevsky", text: "«Beauty will save the world.»" },
    { author: "Antoine de Saint-Exupéry", text: "«It is only with the heart that one can see rightly.»" },
    { author: "Oscar Wilde", text: "«Be yourself.»" },
    { author: "Oscar Wilde", text: "«Beauty is a form of genius.»" },
    { author: "Oscar Wilde", text: "«To love oneself is the beginning of a lifelong romance.»" },
    { author: "Mark Twain", text: "«Begin.»" },
    { author: "Ernest Hemingway", text: "«A man can be destroyed but not defeated.»" },
    { author: "Rumi", text: "«What you seek is seeking you.»" },
    { author: "Rumi", text: "«Beauty is the light of the soul.»" },
    { author: "Khalil Gibran", text: "«Beauty is eternity gazing at itself in a mirror.»" },
    { author: "Paulo Coelho", text: "«When you want something, the whole universe helps you.»" },
    { author: "Haruki Murakami", text: "«Pain is inevitable. Suffering is optional.»" },
    { author: "Coco Chanel", text: "«Beauty begins the moment you decide to be yourself.»" },
    { author: "Leonardo da Vinci", text: "«Simplicity is the ultimate sophistication.»" },
    { author: "Michelangelo", text: "«Beauty is already in the stone.»" },
    { author: "Vincent van Gogh", text: "«Beauty is everywhere.»" },
    { author: "Audrey Hepburn", text: "«The beauty of a woman is seen in her eyes.»" },
    { author: "Marilyn Monroe", text: "«True beauty lies in individuality.»" },
    { author: "Sophia Loren", text: "«Beauty is confidence.»" },
    { author: "Rihanna", text: "«Beauty starts with confidence.»" },
    { author: "Marcus Aurelius", text: "«You become what you think about.»" },
    { author: "Steve Jobs", text: "«Stay hungry. Stay foolish.»" },
    { author: "Steve Jobs", text: "«Follow your heart.»" },
    { author: "Walt Disney", text: "«If you can dream it, you can do it.»" },
    { author: "Nelson Mandela", text: "«I never lose. I either win or learn.»" },
    { author: "Mahatma Gandhi", text: "«Be the change you wish to see in the world.»" },
    { author: "Maya Angelou", text: "«We rise by lifting others.»" },
    { author: "Dalai Lama", text: "«Happiness is a state of mind.»" },
    { author: "Bruce Lee", text: "«Be like water.»" },
    { author: "John Lennon", text: "«Life is what happens while you're making other plans.»" },
    { author: "Mother Teresa", text: "«Love begins with a smile.»" },
    { author: "Hippocrates", text: "«Let food be thy medicine.»" },
    { author: "Benjamin Franklin", text: "«An investment in knowledge pays the best interest.»" },
    { author: "Thomas Edison", text: "«Genius is 1% inspiration and 99% perspiration.»" },
    { author: "Voltaire", text: "«Doubt is the beginning of wisdom.»" },
    { author: "Ralph Waldo Emerson", text: "«Beauty is in the eye of the beholder.»" },
    { author: "George Bernard Shaw", text: "«Life is not about finding yourself but creating yourself.»" },
  ],
  de: [
    { author: "Socrates", text: "«Erkenne dich selbst.»" },
    { author: "Socrates", text: "«Schönheit ist Harmonie.»" },
    { author: "Friedrich Nietzsche", text: "«Wer ein Warum hat, erträgt fast jedes Wie.»" },
    { author: "Friedrich Nietzsche", text: "«Schönheit ist ein Versprechen des Glücks.»" },
    { author: "Albert Einstein", text: "«Fantasie ist wichtiger als Wissen.»" },
    { author: "Albert Einstein", text: "«Alles Schöne ist einfach.»" },
    { author: "Marcus Aurelius", text: "«Unser Leben ist das, was unsere Gedanken daraus machen.»" },
    { author: "Marcus Aurelius", text: "«Charakterschönheit ist wichtiger als äußere Erscheinung.»" },
    { author: "Confucius", text: "«Hör nicht auf.»" },
    { author: "Confucius", text: "«Alles hat Schönheit, aber nicht jeder sieht sie.»" },
    { author: "Confucius", text: "«Eine Reise von tausend Meilen beginnt mit einem Schritt.»" },
    { author: "Seneca", text: "«Wir leiden mehr in der Vorstellung als in der Wirklichkeit.»" },
    { author: "Seneca", text: "«Wahre Schönheit liegt in der Seele.»" },
    { author: "Epictetus", text: "«Kontrolliere deine Reaktion, nicht die Ereignisse.»" },
    { author: "Plato", text: "«Der Anfang ist das Wichtigste.»" },
    { author: "Plato", text: "«Schönheit ist der Glanz der Wahrheit.»" },
    { author: "Aristotle", text: "«Glück liegt im Handeln.»" },
    { author: "Aristotle", text: "«Schönheit ist ein Geschenk der Natur.»" },
    { author: "Immanuel Kant", text: "«Denke selbst.»" },
    { author: "Blaise Pascal", text: "«Das Herz hat Gründe, die die Vernunft nicht kennt.»" },
    { author: "Carl Jung", text: "«Schau nach innen.»" },
    { author: "Leo Tolstoy", text: "«Wo Liebe ist, da ist Leben.»" },
    { author: "Fyodor Dostoevsky", text: "«Schönheit wird die Welt retten.»" },
    { author: "Antoine de Saint-Exupéry", text: "«Man sieht nur mit dem Herzen gut.»" },
    { author: "Oscar Wilde", text: "«Sei du selbst.»" },
    { author: "Oscar Wilde", text: "«Schönheit ist eine Form des Genies.»" },
    { author: "Rumi", text: "«Was du suchst, sucht auch dich.»" },
    { author: "Paulo Coelho", text: "«Wenn du etwas wirklich willst, hilft dir das ganze Universum.»" },
    { author: "Haruki Murakami", text: "«Schmerz ist unvermeidlich. Leiden ist eine Wahl.»" },
    { author: "Coco Chanel", text: "«Schönheit beginnt in dem Moment, in dem du entscheidest, du selbst zu sein.»" },
    { author: "Leonardo da Vinci", text: "«Einfachheit ist die höchste Vollendung.»" },
    { author: "Vincent van Gogh", text: "«Schönheit ist überall.»" },
    { author: "Audrey Hepburn", text: "«Die Schönheit einer Frau liegt in ihren Augen.»" },
    { author: "Steve Jobs", text: "«Bleib hungrig. Bleib unbesonnen.»" },
    { author: "Walt Disney", text: "«Wenn du es träumen kannst, kannst du es tun.»" },
    { author: "Nelson Mandela", text: "«Ich verliere nie. Entweder gewinne ich oder ich lerne.»" },
    { author: "Mahatma Gandhi", text: "«Sei der Wandel, den du in der Welt sehen möchtest.»" },
    { author: "Bruce Lee", text: "«Sei wie Wasser.»" },
    { author: "Dalai Lama", text: "«Glück ist ein Geisteszustand.»" },
    { author: "Benjamin Franklin", text: "«Investitionen in Wissen bringen die besten Zinsen.»" },
    { author: "Voltaire", text: "«Zweifel ist der Beginn der Weisheit.»" },
    { author: "Ralph Waldo Emerson", text: "«Schönheit liegt im Auge des Betrachters.»" },
  ],
  uk: [
    { author: "Socrates", text: "«Пізнай самого себе.»" },
    { author: "Socrates", text: "«Краса — це гармонія.»" },
    { author: "Friedrich Nietzsche", text: "«Той, хто має навіщо жити, витримає майже будь-яке як.»" },
    { author: "Friedrich Nietzsche", text: "«Краса — обіцянка щастя.»" },
    { author: "Albert Einstein", text: "«Уява важливіша за знання.»" },
    { author: "Albert Einstein", text: "«Все красиве — просте.»" },
    { author: "Marcus Aurelius", text: "«Наше життя — це те, що ми про нього думаємо.»" },
    { author: "Marcus Aurelius", text: "«Краса характеру важливіша за зовнішність.»" },
    { author: "Confucius", text: "«Не зупиняйся.»" },
    { author: "Confucius", text: "«Все має красу, але не кожен її бачить.»" },
    { author: "Confucius", text: "«Шлях у тисячу миль починається з одного кроку.»" },
    { author: "Seneca", text: "«Ми страждаємо більше в уяві, ніж насправді.»" },
    { author: "Seneca", text: "«Справжня краса — у душі.»" },
    { author: "Epictetus", text: "«Контролюй реакцію, а не події.»" },
    { author: "Plato", text: "«Початок — найголовніше.»" },
    { author: "Plato", text: "«Краса — це сяйво істини.»" },
    { author: "Aristotle", text: "«Щастя — у вчинках.»" },
    { author: "Immanuel Kant", text: "«Думай самостійно.»" },
    { author: "Blaise Pascal", text: "«Серце має причини, яких розум не знає.»" },
    { author: "Carl Jung", text: "«Дивись всередину.»" },
    { author: "Leo Tolstoy", text: "«Де любов, там і життя.»" },
    { author: "Fyodor Dostoevsky", text: "«Краса врятує світ.»" },
    { author: "Antoine de Saint-Exupéry", text: "«Головного очима не побачиш.»" },
    { author: "Oscar Wilde", text: "«Будь собою.»" },
    { author: "Oscar Wilde", text: "«Краса — форма генія.»" },
    { author: "Rumi", text: "«Ти шукаєш те, що шукає тебе.»" },
    { author: "Rumi", text: "«Краса — це світло душі.»" },
    { author: "Paulo Coelho", text: "«Коли ти чогось хочеш, весь всесвіт допомагає тобі.»" },
    { author: "Haruki Murakami", text: "«Біль неминучий. Страждання — вибір.»" },
    { author: "Coco Chanel", text: "«Краса починається з рішення бути собою.»" },
    { author: "Leonardo da Vinci", text: "«Простота — найвища досконалість.»" },
    { author: "Vincent van Gogh", text: "«Краса всюди.»" },
    { author: "Audrey Hepburn", text: "«Краса жінки — у її очах.»" },
    { author: "Khalil Gibran", text: "«Краса — вічність, що дивиться на себе у дзеркало.»" },
    { author: "Steve Jobs", text: "«Залишайся голодним. Залишайся безрозсудним.»" },
    { author: "Walt Disney", text: "«Якщо можеш мріяти — можеш зробити.»" },
    { author: "Nelson Mandela", text: "«Я ніколи не програю. Я або перемагаю, або навчаюсь.»" },
    { author: "Mahatma Gandhi", text: "«Стань тією зміною, яку хочеш бачити у світі.»" },
    { author: "Bruce Lee", text: "«Будь як вода.»" },
    { author: "Dalai Lama", text: "«Щастя — це стан розуму.»" },
    { author: "Benjamin Franklin", text: "«Інвестиції у знання дають найкращий відсоток.»" },
    { author: "Voltaire", text: "«Сумнів — початок мудрості.»" },
  ],
  es: [
    { author: "Socrates", text: "«Conócete a ti mismo.»" },
    { author: "Socrates", text: "«La belleza es armonía.»" },
    { author: "Friedrich Nietzsche", text: "«Quien tiene un porqué soporta casi cualquier cómo.»" },
    { author: "Friedrich Nietzsche", text: "«La belleza es una promesa de felicidad.»" },
    { author: "Albert Einstein", text: "«La imaginación es más importante que el conocimiento.»" },
    { author: "Albert Einstein", text: "«Todo lo bello es simple.»" },
    { author: "Marcus Aurelius", text: "«Nuestra vida es lo que nuestros pensamientos hacen de ella.»" },
    { author: "Confucius", text: "«No te detengas.»" },
    { author: "Confucius", text: "«Todo tiene belleza, pero no todos la ven.»" },
    { author: "Confucius", text: "«Un viaje de mil millas comienza con un solo paso.»" },
    { author: "Seneca", text: "«Sufrimos más en la imaginación que en la realidad.»" },
    { author: "Seneca", text: "«La verdadera belleza está en el alma.»" },
    { author: "Epictetus", text: "«Controla tu reacción, no los eventos.»" },
    { author: "Plato", text: "«El principio es lo más importante.»" },
    { author: "Plato", text: "«La belleza es el esplendor de la verdad.»" },
    { author: "Aristotle", text: "«La felicidad está en la acción.»" },
    { author: "Immanuel Kant", text: "«Piensa por ti mismo.»" },
    { author: "Blaise Pascal", text: "«El corazón tiene razones que la razón no conoce.»" },
    { author: "Carl Jung", text: "«Mira hacia adentro.»" },
    { author: "Leo Tolstoy", text: "«Donde hay amor, hay vida.»" },
    { author: "Fyodor Dostoevsky", text: "«La belleza salvará al mundo.»" },
    { author: "Antoine de Saint-Exupéry", text: "«Solo se ve bien con el corazón.»" },
    { author: "Oscar Wilde", text: "«Sé tú mismo.»" },
    { author: "Oscar Wilde", text: "«La belleza es una forma de genio.»" },
    { author: "Rumi", text: "«Lo que buscas te está buscando.»" },
    { author: "Paulo Coelho", text: "«Cuando quieres algo, el universo entero conspira para ayudarte.»" },
    { author: "Haruki Murakami", text: "«El dolor es inevitable. El sufrimiento es opcional.»" },
    { author: "Coco Chanel", text: "«La belleza comienza cuando decides ser tú mismo.»" },
    { author: "Leonardo da Vinci", text: "«La simplicidad es la máxima sofisticación.»" },
    { author: "Vincent van Gogh", text: "«La belleza está en todas partes.»" },
    { author: "Audrey Hepburn", text: "«La belleza de una mujer está en sus ojos.»" },
    { author: "Steve Jobs", text: "«Sigue hambriento. Sigue siendo imprudente.»" },
    { author: "Walt Disney", text: "«Si puedes soñarlo, puedes hacerlo.»" },
    { author: "Nelson Mandela", text: "«Nunca pierdo. O gano o aprendo.»" },
    { author: "Mahatma Gandhi", text: "«Sé el cambio que deseas ver en el mundo.»" },
    { author: "Bruce Lee", text: "«Sé como el agua.»" },
    { author: "Dalai Lama", text: "«La felicidad es un estado mental.»" },
    { author: "Benjamin Franklin", text: "«La inversión en conocimiento paga el mejor interés.»" },
    { author: "Voltaire", text: "«La duda es el comienzo de la sabiduría.»" },
    { author: "Ralph Waldo Emerson", text: "«La belleza está en los ojos del que mira.»" },
  ],
  fr: [
    { author: "Socrates", text: "«Connais-toi toi-même.»" },
    { author: "Socrates", text: "«La beauté est harmonie.»" },
    { author: "Friedrich Nietzsche", text: "«Celui qui a un pourquoi peut supporter presque n'importe quel comment.»" },
    { author: "Friedrich Nietzsche", text: "«La beauté est une promesse de bonheur.»" },
    { author: "Albert Einstein", text: "«L'imagination est plus importante que le savoir.»" },
    { author: "Albert Einstein", text: "«Tout ce qui est beau est simple.»" },
    { author: "Marcus Aurelius", text: "«Notre vie est ce que nos pensées en font.»" },
    { author: "Confucius", text: "«Ne t'arrête pas.»" },
    { author: "Confucius", text: "«Tout a de la beauté, mais tout le monde ne la voit pas.»" },
    { author: "Confucius", text: "«Un voyage de mille lieues commence par un seul pas.»" },
    { author: "Seneca", text: "«Nous souffrons plus en imagination qu'en réalité.»" },
    { author: "Seneca", text: "«La vraie beauté est dans l'âme.»" },
    { author: "Epictetus", text: "«Contrôle ta réaction, pas les événements.»" },
    { author: "Plato", text: "«Le commencement est le plus important.»" },
    { author: "Plato", text: "«La beauté est la splendeur de la vérité.»" },
    { author: "Aristotle", text: "«Le bonheur est dans l'action.»" },
    { author: "Immanuel Kant", text: "«Pense par toi-même.»" },
    { author: "Blaise Pascal", text: "«Le cœur a ses raisons que la raison ne connaît pas.»" },
    { author: "Carl Jung", text: "«Regarde en toi.»" },
    { author: "Leo Tolstoy", text: "«Là où il y a de l'amour, il y a de la vie.»" },
    { author: "Fyodor Dostoevsky", text: "«La beauté sauvera le monde.»" },
    { author: "Antoine de Saint-Exupéry", text: "«On ne voit bien qu'avec le cœur.»" },
    { author: "Oscar Wilde", text: "«Sois toi-même.»" },
    { author: "Oscar Wilde", text: "«La beauté est une forme de génie.»" },
    { author: "Rumi", text: "«Ce que tu cherches te cherche aussi.»" },
    { author: "Paulo Coelho", text: "«Quand tu veux quelque chose, tout l'univers t'aide.»" },
    { author: "Haruki Murakami", text: "«La douleur est inévitable. La souffrance est un choix.»" },
    { author: "Coco Chanel", text: "«La beauté commence quand tu décides d'être toi-même.»" },
    { author: "Leonardo da Vinci", text: "«La simplicité est la sophistication suprême.»" },
    { author: "Vincent van Gogh", text: "«La beauté est partout.»" },
    { author: "Audrey Hepburn", text: "«La beauté d'une femme est dans ses yeux.»" },
    { author: "Steve Jobs", text: "«Reste affamé. Reste fou.»" },
    { author: "Walt Disney", text: "«Si tu peux le rêver, tu peux le faire.»" },
    { author: "Nelson Mandela", text: "«Je ne perds jamais. Soit je gagne, soit j'apprends.»" },
    { author: "Mahatma Gandhi", text: "«Sois le changement que tu veux voir dans le monde.»" },
    { author: "Bruce Lee", text: "«Sois comme l'eau.»" },
    { author: "Dalai Lama", text: "«Le bonheur est un état d'esprit.»" },
    { author: "Benjamin Franklin", text: "«Investir dans la connaissance rapporte le meilleur intérêt.»" },
    { author: "Voltaire", text: "«Le doute est le commencement de la sagesse.»" },
    { author: "Ralph Waldo Emerson", text: "«La beauté est dans les yeux de celui qui regarde.»" },
  ],
  it: [
    { author: "Socrates", text: "«Conosci te stesso.»" },
    { author: "Socrates", text: "«La bellezza è armonia.»" },
    { author: "Friedrich Nietzsche", text: "«Chi ha un perché riesce a sopportare quasi qualsiasi come.»" },
    { author: "Friedrich Nietzsche", text: "«La bellezza è una promessa di felicità.»" },
    { author: "Albert Einstein", text: "«L'immaginazione è più importante della conoscenza.»" },
    { author: "Albert Einstein", text: "«Tutto ciò che è bello è semplice.»" },
    { author: "Marcus Aurelius", text: "«La nostra vita è ciò che i nostri pensieri ne fanno.»" },
    { author: "Confucius", text: "«Non fermarti.»" },
    { author: "Confucius", text: "«Tutto ha bellezza, ma non tutti la vedono.»" },
    { author: "Confucius", text: "«Un viaggio di mille miglia inizia con un solo passo.»" },
    { author: "Seneca", text: "«Soffriamo più nell'immaginazione che nella realtà.»" },
    { author: "Seneca", text: "«La vera bellezza è nell'anima.»" },
    { author: "Epictetus", text: "«Controlla la tua reazione, non gli eventi.»" },
    { author: "Plato", text: "«L'inizio è la parte più importante.»" },
    { author: "Plato", text: "«La bellezza è lo splendore della verità.»" },
    { author: "Aristotle", text: "«La felicità sta nelle azioni.»" },
    { author: "Immanuel Kant", text: "«Pensa con la tua testa.»" },
    { author: "Blaise Pascal", text: "«Il cuore ha ragioni che la ragione non conosce.»" },
    { author: "Carl Jung", text: "«Guarda dentro di te.»" },
    { author: "Leo Tolstoy", text: "«Dove c'è amore, c'è vita.»" },
    { author: "Fyodor Dostoevsky", text: "«La bellezza salverà il mondo.»" },
    { author: "Antoine de Saint-Exupéry", text: "«Non si vede bene che col cuore.»" },
    { author: "Oscar Wilde", text: "«Sii te stesso.»" },
    { author: "Oscar Wilde", text: "«La bellezza è una forma di genio.»" },
    { author: "Rumi", text: "«Ciò che cerchi ti sta cercando.»" },
    { author: "Paulo Coelho", text: "«Quando vuoi qualcosa, tutto l'universo ti aiuta.»" },
    { author: "Haruki Murakami", text: "«Il dolore è inevitabile. La sofferenza è una scelta.»" },
    { author: "Coco Chanel", text: "«La bellezza inizia nel momento in cui decidi di essere te stesso.»" },
    { author: "Leonardo da Vinci", text: "«La semplicità è la massima sofisticazione.»" },
    { author: "Vincent van Gogh", text: "«La bellezza è ovunque.»" },
    { author: "Audrey Hepburn", text: "«La bellezza di una donna è nei suoi occhi.»" },
    { author: "Steve Jobs", text: "«Resta affamato. Resta folle.»" },
    { author: "Walt Disney", text: "«Se puoi sognarlo, puoi farlo.»" },
    { author: "Nelson Mandela", text: "«Non perdo mai. O vinco o imparo.»" },
    { author: "Mahatma Gandhi", text: "«Sii il cambiamento che vuoi vedere nel mondo.»" },
    { author: "Bruce Lee", text: "«Sii come l'acqua.»" },
    { author: "Dalai Lama", text: "«La felicità è uno stato mentale.»" },
    { author: "Benjamin Franklin", text: "«Investire nella conoscenza paga il miglior interesse.»" },
    { author: "Voltaire", text: "«Il dubbio è l'inizio della saggezza.»" },
    { author: "Ralph Waldo Emerson", text: "«La bellezza è negli occhi di chi guarda.»" },
  ],
  tr: [
    { author: "Socrates", text: "«Kendini tanı.»" },
    { author: "Socrates", text: "«Güzellik uyumdur.»" },
    { author: "Friedrich Nietzsche", text: "«Yaşamak için bir nedeni olan, neredeyse her şekilde yaşayabilir.»" },
    { author: "Friedrich Nietzsche", text: "«Güzellik mutluluğun vaadidir.»" },
    { author: "Albert Einstein", text: "«Hayal gücü bilgiden daha önemlidir.»" },
    { author: "Albert Einstein", text: "«Her güzel şey basittir.»" },
    { author: "Marcus Aurelius", text: "«Hayatımız düşüncelerimizin bizi götürdüğü yerdir.»" },
    { author: "Confucius", text: "«Dur ma.»" },
    { author: "Confucius", text: "«Her şeyin güzelliği vardır, ama herkes göremez.»" },
    { author: "Confucius", text: "«Bin millik yolculuk tek bir adımla başlar.»" },
    { author: "Seneca", text: "«Gerçekten çok hayal gücümüzde acı çekeriz.»" },
    { author: "Seneca", text: "«Gerçek güzellik ruhun içindedir.»" },
    { author: "Epictetus", text: "«Tepkini kontrol et, olayları değil.»" },
    { author: "Plato", text: "«Başlangıç en önemli kısımdır.»" },
    { author: "Plato", text: "«Güzellik gerçeğin parlaklığıdır.»" },
    { author: "Aristotle", text: "«Mutluluk eylemde yatar.»" },
    { author: "Immanuel Kant", text: "«Kendi başına düşün.»" },
    { author: "Blaise Pascal", text: "«Kalbin aklın bilmediği nedenleri vardır.»" },
    { author: "Carl Jung", text: "«İçine bak.»" },
    { author: "Leo Tolstoy", text: "«Sevgi olan yerde hayat vardır.»" },
    { author: "Fyodor Dostoevsky", text: "«Güzellik dünyayı kurtaracak.»" },
    { author: "Antoine de Saint-Exupéry", text: "«İnsan ancak kalbiyle görür.»" },
    { author: "Oscar Wilde", text: "«Kendine ol.»" },
    { author: "Oscar Wilde", text: "«Güzellik bir deha biçimidir.»" },
    { author: "Rumi", text: "«Aradığın şey seni arıyor.»" },
    { author: "Paulo Coelho", text: "«Bir şeyi gerçekten istediğinde, evren sana yardım eder.»" },
    { author: "Haruki Murakami", text: "«Acı kaçınılmazdır. Acı çekmek bir seçimdir.»" },
    { author: "Coco Chanel", text: "«Güzellik kendin olmaya karar verdiğinde başlar.»" },
    { author: "Leonardo da Vinci", text: "«Sadelik en yüce mükemmeliyettir.»" },
    { author: "Vincent van Gogh", text: "«Güzellik her yerdedir.»" },
    { author: "Audrey Hepburn", text: "«Bir kadının güzelliği gözlerinde yatar.»" },
    { author: "Steve Jobs", text: "«Aç kal. Çılgın kal.»" },
    { author: "Walt Disney", text: "«Hayal edebilirsen, yapabilirsin.»" },
    { author: "Nelson Mandela", text: "«Asla kaybetmem. Ya kazanırım ya da öğrenirim.»" },
    { author: "Mahatma Gandhi", text: "«Dünyada görmek istediğin değişim ol.»" },
    { author: "Bruce Lee", text: "«Su gibi ol.»" },
    { author: "Dalai Lama", text: "«Mutluluk bir zihin halidir.»" },
    { author: "Benjamin Franklin", text: "«Bilgiye yapılan yatırım en iyi faizi verir.»" },
    { author: "Voltaire", text: "«Şüphe bilgeliğin başlangıcıdır.»" },
    { author: "Ralph Waldo Emerson", text: "«Güzellik görenin gözündedir.»" },
  ],
  ar: [
    { author: "Socrates", text: "«اعرف نفسك.»" },
    { author: "Socrates", text: "«الجمال توافق وانسجام.»" },
    { author: "Friedrich Nietzsche", text: "«من يملك السبب يتحمل أي كيف.»" },
    { author: "Friedrich Nietzsche", text: "«الجمال وعد بالسعادة.»" },
    { author: "Albert Einstein", text: "«الخيال أهم من المعرفة.»" },
    { author: "Albert Einstein", text: "«كل ما هو جميل بسيط.»" },
    { author: "Marcus Aurelius", text: "«حياتنا هي ما تصنعه أفكارنا.»" },
    { author: "Confucius", text: "«لا تتوقف.»" },
    { author: "Confucius", text: "«كل شيء له جمال لكن ليس الجميع يراه.»" },
    { author: "Confucius", text: "«رحلة الألف ميل تبدأ بخطوة واحدة.»" },
    { author: "Seneca", text: "«نعاني أكثر في الخيال مما في الواقع.»" },
    { author: "Seneca", text: "«الجمال الحقيقي في الروح.»" },
    { author: "Epictetus", text: "«تحكم في ردة فعلك لا في الأحداث.»" },
    { author: "Plato", text: "«البداية هي الأهم.»" },
    { author: "Plato", text: "«الجمال بريق الحقيقة.»" },
    { author: "Aristotle", text: "«السعادة في الفعل.»" },
    { author: "Immanuel Kant", text: "«فكر بنفسك.»" },
    { author: "Blaise Pascal", text: "«للقلب أسباب لا يعرفها العقل.»" },
    { author: "Carl Jung", text: "«انظر إلى الداخل.»" },
    { author: "Leo Tolstoy", text: "«حيث الحب يكون الحياة.»" },
    { author: "Fyodor Dostoevsky", text: "«الجمال سينقذ العالم.»" },
    { author: "Antoine de Saint-Exupéry", text: "«لا يُرى جيداً إلا بالقلب.»" },
    { author: "Oscar Wilde", text: "«كن نفسك.»" },
    { author: "Oscar Wilde", text: "«الجمال شكل من أشكال العبقرية.»" },
    { author: "Rumi", text: "«ما تبحث عنه يبحث عنك.»" },
    { author: "Paulo Coelho", text: "«حين تريد شيئاً، يساعدك الكون كله.»" },
    { author: "Haruki Murakami", text: "«الألم حتمي. المعاناة اختيار.»" },
    { author: "Coco Chanel", text: "«الجمال يبدأ حين تقرر أن تكوني نفسك.»" },
    { author: "Leonardo da Vinci", text: "«البساطة هي أعلى درجات الرقي.»" },
    { author: "Vincent van Gogh", text: "«الجمال في كل مكان.»" },
    { author: "Audrey Hepburn", text: "«جمال المرأة في عينيها.»" },
    { author: "Steve Jobs", text: "«ابقَ جائعاً. ابقَ أحمق.»" },
    { author: "Walt Disney", text: "«إذا كنت تستطيع أن تحلم فأنت تستطيع أن تفعل.»" },
    { author: "Nelson Mandela", text: "«لا أخسر أبداً. إما أن أفوز أو أتعلم.»" },
    { author: "Mahatma Gandhi", text: "«كن التغيير الذي تريد رؤيته في العالم.»" },
    { author: "Bruce Lee", text: "«كن مثل الماء.»" },
    { author: "Dalai Lama", text: "«السعادة حالة ذهنية.»" },
    { author: "Benjamin Franklin", text: "«الاستثمار في المعرفة يعطي أفضل عائد.»" },
    { author: "Voltaire", text: "«الشك بداية الحكمة.»" },
    { author: "Ralph Waldo Emerson", text: "«الجمال في عين الناظر.»" },
  ],
};
 
function getRandomQuote(lang: Language): Quote {
  const list = QUOTES[lang] || QUOTES.en;
  return list[Math.floor(Math.random() * list.length)];
}
 
interface Props {
  isVisible: boolean;
  lang: Language;
}
 
export function LoadingScreen({ isVisible, lang }: Props) {
  const [quote, setQuote] = useState<Quote>(() => getRandomQuote(lang));
 
  useEffect(() => {
    if (isVisible) {
      setQuote(getRandomQuote(lang));
    }
  }, [isVisible, lang]);
 
  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-40 flex flex-col items-center justify-center bg-[#FDFBF7]/95 backdrop-blur-sm px-8"
        >
          <div className="w-16 h-[1px] bg-[#D4C3A3] mb-10" />
 
          <motion.div
            key={quote.text}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-sm text-center"
          >
            <p className="font-serif text-lg text-[#2C3E50] leading-relaxed mb-4 italic">
              {quote.text}
            </p>
            <p className="text-xs tracking-[0.2em] text-[#B89F7A] uppercase">
              — {quote.author}
            </p>
          </motion.div>
 
          <div className="w-16 h-[1px] bg-[#D4C3A3] mt-10 mb-8" />
 
          <div className="flex items-center gap-2 text-[#B89F7A]">
            <Loader2 size={16} className="animate-spin" />
            <span className="text-xs tracking-[0.25em] uppercase">Analyzing...</span>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
